name: CI
on: [push]
jobs:
  build:
    runs-on: macos-13
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up semgrep
      run: |
        brew install semgrep

    - name: Check semgrep version
      run: semgrep --version

    - name: Run semgrep tests
      run: semgrep scan --test --config rules tests